<!DOCTYPE HTML>

<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="http://blog.dev/css/md.css"/>
    <title>Your Website</title>
</head>

<body>

<header>
    <nav>
        <ul>
            <li>Your menu</li>
        </ul>
    </nav>
</header>

<section>

    <article class="markdown-body">
        <?= $article ?>
    </article>

</section>

<footer>
    <p>Copyright 2009 Your name</p>
</footer>

</body>

</html>
